name: temulik
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  equatable: ^2.0.5
  file_picker: ^8.1.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_compass: ^0.8.1
  flutter_launcher_icons: ^0.14.1
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_svg: ^2.0.15
  geolocator: ^13.0.2
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+2
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  path: ^1.9.0
  path_provider: ^2.1.5
  universal_html: ^2.2.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/categories/charger.png
    - assets/categories/dompet.png
    - assets/categories/handphone.png
    - assets/categories/headset.png
    - assets/categories/helm.png
    - assets/categories/hewan.png
    - assets/categories/jam.png
    - assets/categories/kunci.png
    - assets/categories/kuncikos.png
    - assets/categories/lainnya.png
    - assets/categories/laptop.png
    - assets/categories/motor.png
    - assets/categories/orang.png
    - assets/categories/payung.png
    - assets/categories/powerbank.png
    - assets/categories/sandal.png
    - assets/categories/sepatu.png
    - assets/categories/speaker.png
    - assets/categories/tas.png
    - assets/laptop/acernitro.png
    - assets/laptop/acernitro2.jpg
    - assets/laptop/advan.png
    - assets/laptop/dell.png
    - assets/laptop/dell2.jpg
    - assets/laptop/dell3.jpg
    - assets/laptop/hppavillion.png
    - assets/laptop/hppavillion2.jpg
    - assets/laptop/hppavillion3.jpg
    - assets/laptop/hppavillion4.jpg
    - assets/motor/aerox.png
    - assets/motor/beat.png
    - assets/motor/vario.png
    - assets/motor/vario2.jpeg
    - assets/motor/vario3.jpg
    - assets/profile_picture/Adila.png
    - assets/profile_picture/adrian.jpg
    - assets/profile_picture/Ammara.png
    - assets/profile_picture/Bri.png
    - assets/profile_picture/dzakwan.jpg
    - assets/profile_picture/Fahmi.png
    - assets/profile_picture/Jeh.png
    - assets/profile_picture/Malika.png
    - assets/profile_picture/Muthia.png
    - assets/profile_picture/rafi.jpg
    - assets/profile_picture/riko.jpg
    - assets/cancel.svg
    - assets/attach.png
    - assets/date.png
    - assets/time.png
    - assets/question.png
    - assets/loupe.png
