name: temulik
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.4
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_compass: ^0.8.1
  flutter_launcher_icons: ^0.14.1
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_svg: ^2.0.15
  geolocator: ^13.0.2
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+2
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
