// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7AMj936rC4ptyVs0mhd6F62dHcVC7IJc',
    appId: '1:571424080207:web:b492800360949b852c853a',
    messagingSenderId: '571424080207',
    projectId: 'temulik',
    authDomain: 'temulik.firebaseapp.com',
    storageBucket: 'temulik.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8GXIZfnWAra6qHl63L6uaZtgRnQPT4JQ',
    appId: '1:571424080207:android:d082f90a7e61fc9c2c853a',
    messagingSenderId: '571424080207',
    projectId: 'temulik',
    storageBucket: 'temulik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6EAj_zNIHm5PNPFw5KipZMNAUlgZogoA',
    appId: '1:571424080207:ios:07666bacc75b803d2c853a',
    messagingSenderId: '571424080207',
    projectId: 'temulik',
    storageBucket: 'temulik.appspot.com',
    iosBundleId: 'com.soeara.temulik',
  );
}
